version: '3.2'

services:
  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy/site:/srv
      - /opt/caddy/data:/data
      - /opt/caddy/config:/config
    network_mode: host

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - /opt/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_db
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
#      - TRUSTED_PROXIES=localhost
    depends_on:
      - db
      - caddy
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - mysql_db
      - mysql_password
      - mysql_user


  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /opt/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_db
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD='changeme'
    secrets:
      - mysql_db
      - mysql_password
      - mysql_user

secrets:
  nextcloud_admin_password:
    file: /root/secrets/nextcloud_admin_password.txt # put admin password in this file
  nextcloud_admin_user:
    file: /root/secrets/nextcloud_admin_user.txt # put admin username in this file
  mysql_db:
    file: /root/secrets/mysql_db.txt # put postgresql db name in this file
  mysql_password:
    file: /root/secrets/mysql_password.txt # put postgresql password in this file
  mysql_user:
    file: /secrets/root/mysql_user.txt # put postgresql username in this file