version: '3.2'

services:
  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy/site:/srv
      - /opt/caddy/data:/data
      - /opt/caddy/config:/config
#    network_mode: host

  app:
    image: nextcloud
    restart: always
#    ports:
#      - 8080:80
    volumes:
      - /opt/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # - TRUSTED_PROXIES=localhost
    depends_on:
      - db
      - caddy

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /opt/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /opt/postgres:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    command: ["start-dev"]
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: "jdbc:postgresql://postgres:5432/postgres"
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_ADMIN_URL: "http://localhost:${KC_PORT}"
      KC_HOSTNAME_URL: "http://localhost:${KC_PORT}"
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: true
    ports:
      - ${KC_PORT}:8080
    depends_on:
      - postgres


